import Link from 'next/link'
import { Logo } from '@/components/logo'

export const metadata = { title: 'Terms of Service' }

export default function TermsPage() {
  return (
    <div className="flex min-h-dvh flex-col items-center gap-8 bg-background p-6 pb-16">
      <Link href="/" className="pt-2">
        <Logo size="lg" />
      </Link>
      <div className="w-full max-w-2xl rounded-3xl border border-border bg-card p-6 sm:p-8">
        <h1 className="text-xl font-bold tracking-tight">Terms of Service</h1>
        <p className="mt-1 text-xs text-muted-foreground">Last updated August 6, 2026</p>

        <div className="prose-sm mt-6 flex flex-col gap-5 text-sm leading-relaxed text-foreground">
          <p>
            These terms cover your use of FirstTouch. By creating an account, you agree to them. See our{' '}
            <Link href="/privacy" className="font-semibold underline underline-offset-2">
              Privacy Policy
            </Link>{' '}
            for how we handle your data.
          </p>

          <section>
            <h2 className="text-sm font-bold">Who can create an account</h2>
            <p className="mt-1.5 text-muted-foreground">
              Because many FirstTouch players are minors, an account must be created and controlled by an
              adult: a parent or legal guardian of the player(s) using it, or a player who is 18 or older
              creating an account for themselves. By checking the consent box when adding a player profile,
              you&apos;re confirming you fall into one of those categories for that specific player, and
              that you agree to these terms and our Privacy Policy on their behalf.
            </p>
          </section>

          <section>
            <h2 className="text-sm font-bold">What FirstTouch does</h2>
            <p className="mt-1.5 text-muted-foreground">
              FirstTouch lets you upload soccer training clips, receive AI-generated movement analysis and
              coaching feedback on them, ask follow-up questions about that feedback, receive notes from
              human coaches, and book coaching sessions. FirstTouch does not currently process any payments
              — booking a session through the app does not charge you; any future paid features will come
              with their own clearly-disclosed terms before you&apos;re asked to pay anything.
            </p>
          </section>

          <section>
            <h2 className="text-sm font-bold">Your content</h2>
            <p className="mt-1.5 text-muted-foreground">
              You keep ownership of any video you upload. By uploading it, you&apos;re confirming you have
              the right to do so and, if the footage shows someone other than yourself (e.g. your child),
              that you have their consent — or the authority as their parent/guardian — for it to be
              uploaded and analyzed by FirstTouch as described in our Privacy Policy. Don&apos;t upload
              content you don&apos;t have the rights to.
            </p>
          </section>

          <section>
            <h2 className="text-sm font-bold">AI feedback is a starting point, not a guarantee</h2>
            <p className="mt-1.5 text-muted-foreground">
              Feedback, scores, and training plans generated by AI are derived from a low-resolution,
              single-camera estimate of movement — they&apos;re meant to be a helpful, personalized starting
              point, not a certified or perfectly accurate assessment. They are not medical advice and are
              not a substitute for guidance from a qualified human coach or medical professional. Use your
              judgment, especially around anything related to injury or physical strain.
            </p>
          </section>

          <section>
            <h2 className="text-sm font-bold">Acceptable use</h2>
            <p className="mt-1.5 text-muted-foreground">
              Use FirstTouch only for its intended purpose: your own (or your child&apos;s) soccer
              development. Don&apos;t upload content that isn&apos;t yours to share, don&apos;t attempt to
              access another account&apos;s data, and don&apos;t misuse the service in a way that disrupts
              it for other users.
            </p>
          </section>

          <section>
            <h2 className="text-sm font-bold">Ending your account</h2>
            <p className="mt-1.5 text-muted-foreground">
              You can stop using FirstTouch at any time. To request deletion of your account and its data,
              contact us — see the Privacy Policy for details, since there&apos;s no self-serve delete
              button in the app yet.
            </p>
          </section>

          <section>
            <h2 className="text-sm font-bold">No guarantees</h2>
            <p className="mt-1.5 text-muted-foreground">
              FirstTouch is provided as-is, as a developing product. We do our best to keep it reliable and
              accurate, but we don&apos;t guarantee uninterrupted availability or that AI-generated content
              will be error-free.
            </p>
          </section>

          <section>
            <h2 className="text-sm font-bold">Changes to these terms</h2>
            <p className="mt-1.5 text-muted-foreground">
              If these terms change in a meaningful way, we&apos;ll update the date at the top of this page.
            </p>
          </section>

          <section>
            <h2 className="text-sm font-bold">Contact</h2>
            <p className="mt-1.5 text-muted-foreground">
              Questions about these terms:{' '}
              <a href="mailto:arivuganbu@gmail.com" className="font-semibold underline underline-offset-2">
                arivuganbu@gmail.com
              </a>
            </p>
          </section>
        </div>
      </div>
    </div>
  )
}
