'use client'

import Link from 'next/link'
import { useTranslation } from '@/lib/i18n/context'

const LAST_UPDATED_ISO = '2026-08-07'

const content = {
  en: {
    title: 'Terms of Service',
    lastUpdated: 'Last updated August 7, 2026',
    intro: (
      <>
        These terms cover your use of FirstTouch. By creating an account, you agree to them. See our{' '}
        <Link href="/privacy" className="font-semibold underline underline-offset-2">
          Privacy Policy
        </Link>{' '}
        for how we handle your data.
      </>
    ),
    sections: [
      {
        h: 'Who can create an account',
        p: "Because many FirstTouch players are minors, an account must be created and controlled by an adult: a parent or legal guardian of the player(s) using it, or a player who is 18 or older creating an account for themselves. By checking the consent box when adding a player profile, you're confirming you fall into one of those categories for that specific player, and that you agree to these terms and our Privacy Policy on their behalf.",
      },
      {
        h: 'What FirstTouch does',
        p: 'FirstTouch lets you upload soccer training clips, receive AI-generated movement analysis and coaching feedback on them, ask follow-up questions about that feedback, receive notes from human coaches, and book coaching sessions. Every account gets 2 free AI analyses; beyond that, a FirstTouch Pro subscription is required — see "Subscription & billing" below. Booking a coaching session itself does not separately charge you.',
      },
      {
        h: 'Subscription & billing',
        p: "FirstTouch Pro is a monthly subscription, billed to the parent/guardian account (not per player) through our payment processor, Stripe — one subscription covers up to 20 AI clip analyses and 60 AI chat messages per month, shared across every player on your account. The list price is $40/month; new subscribers may see a lower promotional rate at signup, and if you subscribe at a promotional rate you keep that rate for as long as your subscription stays active without a gap. You can cancel anytime from the Manage Billing screen in your Profile tab — your subscription stays active through the end of the billing period you already paid for, and we don't offer refunds for partial periods. If a payment fails, we may pause access until it's resolved. This section is a plain-language draft and, like the rest of this page, should get a real legal review before FirstTouch scales beyond early access — payments raise the stakes beyond what these terms originally covered.",
      },
      {
        h: 'Your content',
        p: "You keep ownership of any video you upload. By uploading it, you're confirming you have the right to do so and, if the footage shows someone other than yourself (e.g. your child), that you have their consent — or the authority as their parent/guardian — for it to be uploaded and analyzed by FirstTouch as described in our Privacy Policy. Don't upload content you don't have the rights to.",
      },
      {
        h: 'AI feedback is a starting point, not a guarantee',
        p: "Feedback, scores, and training plans generated by AI are derived from a low-resolution, single-camera estimate of movement — they're meant to be a helpful, personalized starting point, not a certified or perfectly accurate assessment. They are not medical advice and are not a substitute for guidance from a qualified human coach or medical professional. Use your judgment, especially around anything related to injury or physical strain.",
      },
      {
        h: 'Acceptable use',
        p: "Use FirstTouch only for its intended purpose: your own (or your child's) soccer development. Don't upload content that isn't yours to share, don't attempt to access another account's data, and don't misuse the service in a way that disrupts it for other users.",
      },
      {
        h: 'Ending your account',
        p: "You can stop using FirstTouch at any time. To request deletion of your account and its data, contact us — see the Privacy Policy for details, since there's no self-serve delete button in the app yet.",
      },
      {
        h: 'No guarantees',
        p: "FirstTouch is provided as-is, as a developing product. We do our best to keep it reliable and accurate, but we don't guarantee uninterrupted availability or that AI-generated content will be error-free.",
      },
      {
        h: 'Changes to these terms',
        p: "If these terms change in a meaningful way, we'll update the date at the top of this page.",
      },
    ],
    contactLabel: 'Questions about these terms:',
  },
  ru: {
    title: 'Условия использования',
    lastUpdated: 'Обновлено 7 августа 2026 г.',
    intro: (
      <>
        Эти условия регулируют использование FirstTouch. Создавая аккаунт, вы соглашаетесь с ними.
        Подробнее о том, как мы обрабатываем ваши данные — в нашей{' '}
        <Link href="/privacy" className="font-semibold underline underline-offset-2">
          Политике конфиденциальности
        </Link>
        .
      </>
    ),
    sections: [
      {
        h: 'Кто может создать аккаунт',
        p: 'Поскольку многие игроки FirstTouch — несовершеннолетние, аккаунт должен создавать и контролировать взрослый: родитель или законный опекун игрока(ов), либо игрок в возрасте 18 лет и старше, создающий аккаунт для себя. Отмечая галочку согласия при добавлении профиля игрока, вы подтверждаете, что относитесь к одной из этих категорий для этого конкретного игрока, и что принимаете эти условия и нашу Политику конфиденциальности от его имени.',
      },
      {
        h: 'Что делает FirstTouch',
        p: 'FirstTouch позволяет загружать тренировочные ролики по футболу, получать сгенерированный ИИ анализ движения и разбор от тренера по ним, задавать уточняющие вопросы по этому разбору, получать заметки от живых тренеров и бронировать тренерские сессии. Каждый аккаунт получает 2 бесплатных ИИ-анализа; сверх этого требуется подписка FirstTouch Pro — см. «Подписка и оплата» ниже. Само бронирование тренерской сессии отдельно не оплачивается.',
      },
      {
        h: 'Подписка и оплата',
        p: 'FirstTouch Pro — это ежемесячная подписка, оплата которой привязана к аккаунту родителя/опекуна (а не к отдельному игроку) через нашего платёжного оператора Stripe — одна подписка покрывает до 20 ИИ-анализов роликов и 60 сообщений в ИИ-чате в месяц, общих для всех игроков на вашем аккаунте. Базовая цена — $40/месяц; новые подписчики могут увидеть сниженную промо-цену при регистрации, и если вы оформили подписку по промо-цене, она сохраняется за вами, пока подписка остаётся активной без перерыва. Отменить можно в любой момент в разделе «Управление подпиской» на вкладке Профиль — подписка останется активной до конца уже оплаченного расчётного периода, и мы не возвращаем средства за неполные периоды. Если платёж не прошёл, мы можем приостановить доступ до решения проблемы. Этот раздел — черновик на простом языке и, как и вся эта страница, должен пройти настоящую юридическую проверку до того, как FirstTouch выйдет за рамки раннего доступа — платежи повышают ставки сильнее, чем изначально покрывали эти условия.',
      },
      {
        h: 'Ваш контент',
        p: 'Вы сохраняете право собственности на любое загруженное видео. Загружая его, вы подтверждаете, что имеете на это право, и — если на записи не вы сами, а, например, ваш ребёнок — что у вас есть его согласие (или полномочия родителя/опекуна) на загрузку и анализ этого видео FirstTouch, как описано в нашей Политике конфиденциальности. Не загружайте контент, на который у вас нет прав.',
      },
      {
        h: 'Разбор от ИИ — это отправная точка, а не гарантия',
        p: 'Разборы, оценки и планы тренировок, сгенерированные ИИ, построены на низкоточной оценке движения с одной камеры — они задуманы как полезная, персонализированная отправная точка, а не сертифицированная или идеально точная оценка. Это не медицинская консультация, и они не заменяют рекомендации квалифицированного живого тренера или медицинского специалиста. Полагайтесь на своё суждение, особенно во всём, что касается травм или физической нагрузки.',
      },
      {
        h: 'Допустимое использование',
        p: 'Используйте FirstTouch только по назначению: для развития себя (или своего ребёнка) в футболе. Не загружайте контент, которым у вас нет права делиться, не пытайтесь получить доступ к данным чужого аккаунта и не используйте сервис так, чтобы это мешало другим пользователям.',
      },
      {
        h: 'Закрытие аккаунта',
        p: 'Вы можете прекратить использование FirstTouch в любой момент. Чтобы запросить удаление аккаунта и его данных, свяжитесь с нами — подробности в Политике конфиденциальности, поскольку кнопки самостоятельного удаления в приложении пока нет.',
      },
      {
        h: 'Отсутствие гарантий',
        p: 'FirstTouch предоставляется «как есть», как развивающийся продукт. Мы стараемся поддерживать его надёжность и точность, но не гарантируем бесперебойную доступность или отсутствие ошибок в контенте, сгенерированном ИИ.',
      },
      {
        h: 'Изменения условий',
        p: 'Если эти условия существенно изменятся, мы обновим дату в верхней части этой страницы.',
      },
    ],
    contactLabel: 'Вопросы по этим условиям:',
  },
} as const

export function TermsContent() {
  const { language } = useTranslation()
  const c = content[language]

  return (
    <>
      <h1 className="text-xl font-bold tracking-tight">{c.title}</h1>
      <p className="mt-1 text-xs text-muted-foreground">
        <time dateTime={LAST_UPDATED_ISO}>{c.lastUpdated}</time>
      </p>

      <div className="prose-sm mt-6 flex flex-col gap-5 text-sm leading-relaxed text-foreground">
        <p>{c.intro}</p>

        {c.sections.map((s) => (
          <section key={s.h}>
            <h2 className="text-sm font-bold">{s.h}</h2>
            <p className="mt-1.5 text-muted-foreground">{s.p}</p>
          </section>
        ))}

        <section>
          <h2 className="text-sm font-bold">{language === 'ru' ? 'Контакты' : 'Contact'}</h2>
          <p className="mt-1.5 text-muted-foreground">
            {c.contactLabel}{' '}
            <a href="mailto:arivuganbu@gmail.com" className="font-semibold underline underline-offset-2">
              arivuganbu@gmail.com
            </a>
          </p>
        </section>
      </div>
    </>
  )
}
